/* Source and licensing information for the line(s) below can be found at http://local.aayushientpune.com/core/assets/vendor/jquery-once/jquery.once.min.js. */
/*!
 * jQuery Once v2.2.3 - http://github.com/robloach/jquery-once
 * @license MIT, GPL-2.0
 *   http://opensource.org/licenses/MIT
 *   http://opensource.org/licenses/GPL-2.0
 */
(function(e){"use strict";if(typeof exports==="object"&&typeof exports.nodeName!=="string"){e(require("jquery"))}else if(typeof define==="function"&&define.amd){define(["jquery"],e)}else{e(jQuery)}})(function(t){"use strict";var r=function(e){e=e||"once";if(typeof e!=="string"){throw new TypeError("The jQuery Once id parameter must be a string")}return e};t.fn.once=function(e){var n="jquery-once-"+r(e);return this.filter(function(){return t(this).data(n)!==true}).data(n,true)};t.fn.removeOnce=function(e){return this.findOnce(e).removeData("jquery-once-"+r(e))};t.fn.findOnce=function(e){var n="jquery-once-"+r(e);return this.filter(function(){return t(this).data(n)===true})}});

/* Source and licensing information for the above line(s) can be found at http://local.aayushientpune.com/core/assets/vendor/jquery-once/jquery.once.min.js. */;
/* Source and licensing information for the line(s) below can be found at http://local.aayushientpune.com/core/misc/drupalSettingsLoader.js. */
(function(){var t=document.querySelector('head > script[type="application/json"][data-drupal-selector="drupal-settings-json"], body > script[type="application/json"][data-drupal-selector="drupal-settings-json"]');window.drupalSettings={};if(t!==null){window.drupalSettings=JSON.parse(t.textContent)}})();
/* Source and licensing information for the above line(s) can be found at http://local.aayushientpune.com/core/misc/drupalSettingsLoader.js. */;
/* Source and licensing information for the line(s) below can be found at http://local.aayushientpune.com/core/misc/drupal.js. */
;window.Drupal={behaviors:{},locale:{}};(function(t,e,r,n,o,a){t.throwError=function(t){setTimeout(function(){throw t},0)};t.attachBehaviors=function(r,n){r=r||document;n=n||e;var o=t.behaviors;Object.keys(o||{}).forEach(function(e){if(typeof o[e].attach==='function'){try{o[e].attach(r,n)}catch(a){t.throwError(a)}}})};t.detachBehaviors=function(r,n,o){r=r||document;n=n||e;o=o||'unload';var a=t.behaviors;Object.keys(a||{}).forEach(function(e){if(typeof a[e].detach==='function'){try{a[e].detach(r,n,o)}catch(c){t.throwError(c)}}})};t.checkPlain=function(t){t=t.toString().replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');return t};t.formatString=function(e,r){var n={};Object.keys(r||{}).forEach(function(e){switch(e.charAt(0)){case'@':n[e]=t.checkPlain(r[e]);break;case'!':n[e]=r[e];break;default:n[e]=t.theme('placeholder',r[e]);break}});return t.stringReplace(e,n,null)};t.stringReplace=function(e,r,n){if(e.length===0){return e};if(!Array.isArray(n)){n=Object.keys(r||{});n.sort(function(t,e){return t.length-e.length})};if(n.length===0){return e};var c=n.pop(),a=e.split(c);if(n.length){for(var o=0;o<a.length;o++){a[o]=t.stringReplace(a[o],r,n.slice(0))}};return a.join(r[c])};t.t=function(e,o,n){n=n||{};n.context=n.context||'';if(typeof r!=='undefined'&&r.strings&&r.strings[n.context]&&r.strings[n.context][e]){e=r.strings[n.context][e]};if(o){e=t.formatString(e,o)};return e};t.url=function(t){return e.path.baseUrl+e.path.pathPrefix+t};t.url.toAbsolute=function(t){var r=document.createElement('a');try{t=decodeURIComponent(t)}catch(e){};r.setAttribute('href',t);return r.cloneNode(!1).href};t.url.isLocal=function(r){var n=t.url.toAbsolute(r),c=window.location.protocol;if(c==='http:'&&n.indexOf('https:')===0){c='https:'};var o=''.concat(c,'//').concat(window.location.host).concat(e.path.baseUrl.slice(0,-1));try{n=decodeURIComponent(n)}catch(a){};try{o=decodeURIComponent(o)}catch(a){};return n===o||n.indexOf(''.concat(o,'/'))===0};t.formatPlural=function(n,o,c,a,u){a=a||{};a['@count']=n;var l=e.pluralDelimiter,f=t.t(o+l+c,a,u).split(l),i=0;if(typeof r!=='undefined'&&r.pluralFormula){i=n in r.pluralFormula?r.pluralFormula[n]:r.pluralFormula.default}
else if(a['@count']!==1){i=1};return f[i]};t.encodePath=function(t){return window.encodeURIComponent(t).replace(/%2F/g,'/')};t.deprecationError=function(t){var r=t.message;if(e.suppressDeprecationErrors===!1&&typeof n!=='undefined'&&n.warn){n.warn('[Deprecation] '.concat(r))}};t.deprecatedProperty=function(e){var r=e.target,n=e.deprecatedProperty,c=e.message;if(!o||!a){return r};return new o(r,{get:function(e,r){if(r===n){t.deprecationError({message:c})};for(var i=arguments.length,u=new Array(i>2?i-2:0),o=2;o<i;o++){u[o-2]=arguments[o]};return a.get.apply(a,[e,r].concat(u))}})};t.theme=function(e){if(e in t.theme){var a;for(var n=arguments.length,o=new Array(n>1?n-1:0),r=1;r<n;r++){o[r-1]=arguments[r]};return(a=t.theme)[e].apply(a,o)}};t.theme.placeholder=function(e){return'<em class="placeholder">'.concat(t.checkPlain(e),'</em>')}})(Drupal,window.drupalSettings,window.drupalTranslations,window.console,window.Proxy,window.Reflect);
/* Source and licensing information for the above line(s) can be found at http://local.aayushientpune.com/core/misc/drupal.js. */;
/* Source and licensing information for the line(s) below can be found at http://local.aayushientpune.com/core/misc/drupal.init.js. */
;if(window.jQuery){jQuery.noConflict()};document.documentElement.className+=' js';(function(e,n){var t=function(e){var n=function t(){e();document.removeEventListener('DOMContentLoaded',t)};if(document.readyState!=='loading'){setTimeout(e,0)}
else{document.addEventListener('DOMContentLoaded',n)}};t(function(){e.attachBehaviors(document,n)})})(Drupal,window.drupalSettings);
/* Source and licensing information for the above line(s) can be found at http://local.aayushientpune.com/core/misc/drupal.init.js. */;
/* Source and licensing information for the line(s) below can be found at http://local.aayushientpune.com/modules/google_analytics/js/google_analytics.js. */
(function(t,e,o){"use strict";e.google_analytics={};t(document).ready(function(){t(document.body).on("mousedown keyup touchstart",function(a){t(a.target).closest("a,area").each(function(){if(e.google_analytics.isInternal(this.href)){if(t(this).is(".colorbox")&&(o.google_analytics.trackColorbox)){}
else if(o.google_analytics.trackDownload&&e.google_analytics.isDownload(this.href)){ga("send",{hitType:"event",eventCategory:"Downloads",eventAction:e.google_analytics.getDownloadExtension(this.href).toUpperCase(),eventLabel:e.google_analytics.getPageUrl(this.href),transport:"beacon"})}
else if(e.google_analytics.isInternalSpecial(this.href)){ga("send",{hitType:"pageview",page:e.google_analytics.getPageUrl(this.href),transport:"beacon"})}}
else{if(o.google_analytics.trackMailto&&t(this).is("a[href^='mailto:'],area[href^='mailto:']")){ga("send",{hitType:"event",eventCategory:"Mails",eventAction:"Click",eventLabel:this.href.substring(7),transport:"beacon"})}
else if(o.google_analytics.trackOutbound&&this.href.match(/^\w+:\/\//i)){if(o.google_analytics.trackDomainMode!==2||(o.google_analytics.trackDomainMode===2&&!e.google_analytics.isCrossDomain(this.hostname,o.google_analytics.trackCrossDomains))){ga("send",{hitType:"event",eventCategory:"Outbound links",eventAction:"Click",eventLabel:this.href,transport:"beacon"})}}}})});if(o.google_analytics.trackUrlFragments){window.onhashchange=function(){ga("send",{hitType:"pageview",page:location.pathname+location.search+location.hash})}};if(o.google_analytics.trackColorbox){t(document).on("cbox_complete",function(){var o=t.colorbox.element().attr("href");if(o){ga("send",{hitType:"pageview",page:e.google_analytics.getPageUrl(o)})}})}});e.google_analytics.isCrossDomain=function(e,o){return t.inArray(e,o)>-1?!0:!1};e.google_analytics.isDownload=function(e){var t=new RegExp("\\.("+o.google_analytics.trackDownloadExtensions+")([\?#].*)?$","i");return t.test(e)};e.google_analytics.isInternal=function(e){var t=new RegExp("^(https?):\/\/"+window.location.host,"i");return t.test(e)};e.google_analytics.isInternalSpecial=function(e){var t=new RegExp("(\/go\/.*)$","i");return t.test(e)};e.google_analytics.getPageUrl=function(e){var t=new RegExp("^(https?):\/\/"+window.location.host,"i");return e.replace(t,"")};e.google_analytics.getDownloadExtension=function(e){var a=new RegExp("\\.("+o.google_analytics.trackDownloadExtensions+")([\?#].*)?$","i"),t=a.exec(e);return(t===null)?"":t[1]}})(jQuery,Drupal,drupalSettings);
/* Source and licensing information for the above line(s) can be found at http://local.aayushientpune.com/modules/google_analytics/js/google_analytics.js. */;
